apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-analytics-gui
spec:
  selector:
    matchLabels:
      app: byk-analytics-gui
  template:
    metadata:
      labels:
        app: byk-analytics-gui
    spec:
      containers:
        - name: byk-analytics-gui
          image: "{{ .Values.images.analytics.registry }}/{{ .Values.images.analytics.repository }}:{{ .Values.images.analytics.tag }}"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: REACT_APP_RUUTER_API_URL
              value: "https://ruuter.test.buerokratt.ee/v2/public/backoffice  "
            - name: REACT_APP_RUUTER_V1_PRIVATE_API_URL
              value: "https://ruuter.test.buerokratt.ee/v1/private/"
            - name: REACT_APP_RUUTER_V2_PRIVATE_API_URL
              value: "https://ruuter.test.buerokratt.ee/v2/private/backoffice"
            - name: REACT_APP_MENU_URL
              value: "https://admin.test.buerokratt.ee"
            - name:  REACT_APP_MENU_PATH
              value: "/chat/menu.json"
            - name: REACT_APP_CUSTOMER_SERVICE_LOGIN
              value: "http://admin.test.buerokratt.ee/et/dev-auth"
            - name: REACT_APP_CONVERSATIONS_BASE_URL
              value: "https://admin.test.buerokratt.ee/chat"
            - name: REACT_APP_TRAINING_BASE_URL
              value: "https://admin.test.buerokratt.ee/training"
            - name: REACT_APP_ANALYTICS_BASE_URL
              value: "https://admin.test.buerokratt.ee/analytics"
            - name: REACT_APP_SERVICES_BASE_URL
              value: "https://admin.test.buerokratt.ee/services"
            - name: REACT_APP_SETTINGS_BASE_URL
              value: "https://admin.test.buerokratt.ee/settings"
            - name: REACT_APP_MONITORING_BASE_URL
              value: "https://admin.test.buerokratt.ee/monitoring"
            - name: REACT_APP_SERVICE_ID
              value: "analytics"
            - name: REACT_APP_BUEROKRATT_CHATBOT_URL
              value: http://byk-bot:5005
            - name: REACT_APP_OPENSEARCH_DASHBOARD_URL
              value: https://opensearch.org/ # TODO: replace
            - name: REACT_APP_OPENDATAPORT_URL
              value: https://avaandmed.eesti.ee # TODO: replace
            - name: REACT_APP_API_URL
              value: "https://ruuter.test.buerokratt.ee/v2/private/analytics"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 11
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 11
