apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-analytics-gui
spec:
  selector:
    matchLabels:
      app: byk-analytics-gui
  template:
    metadata:
      labels:
        app: byk-analytics-gui
    spec:
      containers:
        - name: byk-analytics-gui
          image: "{{ .Values.images.analytics.registry }}/{{ .Values.images.analytics.repository }}:{{ .Values.images.analytics.tag }}"
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/.env.development
              subPath: env.development
      volumes:
        - name: config-volume
          configMap:
            name: configmap-byk-analytics
