apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter
spec:
  selector:
    matchLabels:
      app: byk-ruuter
  template:
    metadata:
      labels:
        app: byk-ruuter
    spec:
      containers:
        - name: byk-ruuter
          image: ghcr.io/buerokratt/ruuter:beta-2.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LOG_LEVEL_INFO
              value: WARN
            - name: LOG_LEVEL_TIMING
              value: INFO
          volumeMounts:
            - name: dsl
              mountPath: {{ .Values.byk.ruuter.dsl.path }}
            - name: urls-env
              mountPath: /usr/local/tomcat/urls.env.json
              subPath: public.urls.docker.json
            - name: byk-dsl-services
              mountPath: "/opt/dsl"
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: {{ .Values.byk.dsl.image.registry }}/{{ .Values.byk.dsl.image.repository }}:{{ .Values.byk.dsl.image.tag }}
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL/
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /Ruuter/public/v2/ && mv /Ruuter/public/v2/* /root/DSL/ && echo 'moved'
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
        - name: byk-dsl-services
          persistentVolumeClaim:
            claimName: byk-dsl-services
