apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter-v1
  labels:
    app: byk-ruuter-v1
spec:
  selector:
    matchLabels:
      app: byk-ruuter-v1
  template:
    metadata:
      labels:
        app: byk-ruuter-v1
    spec:
      containers:
        - name: byk-ruuter-v1
          image: ghcr.io/buerokratt/ruuter-1.0:beta-1.1.1
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LOG_LEVEL_INFO
              value: WARN
            - name: LOG_LEVEL_TIMING
              value: INFO
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: dsl
              mountPath: {{ .Values.byk.ruuterV1.dsl.path }}
            - name: urls-env
              mountPath: /usr/local/tomcat/urls.env.json
              subPath: public.urls.docker.json
          livenessProbe:
            httpGet:
              path: /rest/test
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /rest/test
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: {{ .Values.byk.dsl.image.registry }}/{{ .Values.byk.dsl.image.repository }}:{{ .Values.byk.dsl.image.tag }}
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL/
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /Ruuter/public/v1/ && mv /Ruuter/public/v1/* /root/DSL/ && echo 'moved'
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
