apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-node
  template:
    metadata:
      labels:
        app: opensearch-node
    spec:
      containers:
        - name: opensearch-node
          image: opensearchproject/opensearch:latest
          env:
            - name: cluster.name
              value: opensearch-cluster
            - name: node.name
              value: opensearch-node
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9600
              name: opensearch
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          emptyDir: {}
