apiVersion: apps/v1
kind: Deployment
metadata:
  name: byk-ruuter-private
spec:
  selector:
    matchLabels:
      app: byk-ruuter-private
  template:
    metadata:
      labels:
        app: byk-ruuter-private
    spec:
      containers:
        - name: byk-ruuter-private
          image: ghcr.io/buerokratt/ruuter:beta-2.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ruuter.cors.allowedOrigins
              value: http://test.buerokratt.ee:3000
          volumeMounts:
            - name: dsl
              mountPath: {{ .Values.byk.ruuterPrivate.dsl.path }}
            - name: urls-env
              mountPath: /usr/local/tomcat/urls.env.json
              subPath: private.urls.docker.json
            - name: byk-dsl-services
              mountPath: /opt/dsl
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      initContainers:
        - name: dsl-installer
          image: {{ .Values.byk.dsl.image.registry }}/{{ .Values.byk.dsl.image.repository }}:{{ .Values.byk.dsl.image.tag }}
          volumeMounts:
            - name: dsl
              mountPath: /root/DSL/
          command: ["/bin/sh"]
          args:
            - "-c"
            - >
              ls -l /Ruuter/private/v2/ && mv /Ruuter/private/v2/* /root/DSL/ && echo 'moved'
      volumes:
        - name: dsl
          emptyDir: {}
        - name: urls-env
          configMap:
            name: urls-env-config
        - name: byk-dsl-services
          persistentVolumeClaim:
            claimName: byk-dsl-services
