apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anonymizer-gui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST"
#    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "https://test.buerokratt.ee"
#    nginx.ingress.kubernetes.io/session-cookie-samesite: "None"
#    nginx.ingress.kubernetes.io/proxy-set-header: "Content-Type: application/json"
#    nginx.ingress.kubernetes.io/additional-response-headers: "Access-Control-Allow-Headers: Content-Type, Cache-Control"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #cert-manager.io/cluster-issuer: {{ .Values.ingress.certIssuerName | quote }}
  labels:
    name: anonymizer-ingress
spec:
  rules:
  - host: admin.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/anonymizer"
        backend:
          service:
            name: byk-anonymizer
            port:
              number: 3004
  tls:
  - hosts:
    - admin.{{ .Values.domain }}
    secretName: byk-tls-admin-secret 