apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruuter-byk-tim-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, GET, OPTIONS"
#    nginx.ingress.kubernetes.io/cors-allow-headers: "content-type"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "https://admin.test.buerokratt.ee, https://test.buerokratt.ee, https://ruuter.test.buerokratt.ee/v1/public/, https://ruuter.test.buerokratt.ee/v1/private/"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      more_set_headers "Content-Length: 256";
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  labels:
    name: ruuter-byk-tim-ingress
spec:
  rules:
  - host: tim.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: byk-tim
            port:
              number: 8085
  tls:
  - hosts:
    - tim.{{ .Values.domain }}
    secretName: tim.test.buerokratt.ee0503prod 
