apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: byk-ruuter-private
spec:
  host: byk-ruuter-private
  subsets:
  - name: byk-ruuter-private
    labels:
      app: byk-ruuter-private
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: byk-ruuter-private
spec:
  hosts:
  - byk-ruuter-private
  http:
  - name: allow
    match:
    - sourceLabels:
        app: byk-ruuter-private-v1
    route:
    - destination:
        host: byk-ruuter-private
        subset: byk-ruuter-private
  - name: reject
    route:
    - destination:
        host: byk-ruuter-private
        subset: byk-ruuter-private
    fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 403
