apiVersion: v1
kind: Job
metadata:
  name: notifications-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"  # Ensures the hook runs before other resources
spec:
  template:
    spec:
      containers:
      - name: notifications-container
        image: riaee/byk:sse-notifications2603
      restartPolicy: Never
