apiVersion: v1
kind: Service
metadata:
  name: opensearch-node
spec:
  selector:
    app: opensearch-node
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: opensearch
