imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

domain: test.buerokratt.ee # byk.buerokratt.ee

#ingress:
#  tlsConfigMapName: byk-tls-configmap

ingress:
  certIssuerName: letsencrypt-prod-issuer
#  certIssuerName: letsencrypt-staging 

byk:
  dsl:
    image:
      registry: "ghcr.io"
      repository: "buerokratt/buerokratt-dsl"
      tag: "pre-alpha-kube-1.12.33"
  ruuter:
    dsl:
      path: "/DSL/"
  ruuterPrivate:
    dsl:
      path: "/DSL/"
  resql:
    dsl:
      path: "/DSL/"
  dmapper:
    dsl:
      path: "/workspace/app/module"
  dmapper2:
    dsl:
      path: "/workspace/app/module"
  liquibase:
    dsl:
      repo: https://github.com/buerokratt/Buerokratt-Chatbot.git
      path: DSL/Liquibase
  widget:
    index:
      repo: https://github.com/varmoh/Installation-Guides.git
      path: default-setup/backoffice-and-bykstack/chat-widget/index.html
  tim:
    env:
      security:
        allowlist:
          jwt: byk-ruuter,byk-ruuter-private,byk-dmapper,byk-widget,byk-backoffice-login,byk-resql,byk-tim,10.0.0.0/8,192.168.0.0/16
        oauth2:
          client:
            clientId: byk_public_test
            clientSecret: tI6eiKVjASEnKpGBKWSHI1y63Zv69fvh
            scope: openid
            userAuthorizationUri: https://tara-test.ria.ee/oidc/authorize
            accessTokenUri: https://tara-test.ria.ee/oidc/token
          resource:
            jwk:
              keySetUri: https://tara-test.ria.ee/oidc/jwks
      legacyPortalIntegration:
        legacyUrl: arendus.eesti.ee
        legacyPortalRefererMarker: https://arendus.eesti.ee/portaal
        sessionCookieDomain: buerokratt.ee
      jwtIntegration:
        signature:
          issuer: test.buerokratt.ee
          keyStorePassword: ppjjpp
          keyStore: classpath:jwtkeystore.jks
      spring:
        profiles:
          active: dev
      logging:
        level:
          root: TRACE

tim-postgresql:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: tim
    password: "123"
    database: tim

users-db:
  image:
    tag: 14.1.0
  auth:
    postgresPassword: postgres
    username: byk
    password: "01234"
    database: byk
  statefulset:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: true

