name: Kubernetes Deployment using helm charts

on:
  workflow_run:
    workflows: ["Update Chart Version and build tarball"]
    types:
      - completed

jobs:
  check_ci_update_build_chart:
    runs-on: ubuntu-latest
    steps:

    - name: Run simple test step
      run: echo "This is a test step."




