name: Trigger Deploy Workflow
on:
  workflow_run:
    workflows: ["Update and build chart"]
    types:
      - completed

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deploy event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: chart_updated
